<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
	<channel>
		
		<title>Harvesting Evidence</title>
		<link>http://www.harvesting-evidence.org/</link>
		<description>Latest news.</description>
		<language>en</language>
		<image>
			<title>Harvesting Evidence</title>
			<url>http://www.harvesting-evidence.org/EXT:tt_news/ext_icon.gif</url>
			<link>http://www.harvesting-evidence.org/</link>
			<width></width>
			<height></height>
			<description>Latest news.</description>
		</image>
		<generator>TYPO3 - get.content.right</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
		
		
		
		<lastBuildDate>Wed, 15 Jul 2009 00:00:00 +0200</lastBuildDate>
		
		
		<item>
			<title>New website is launched</title>
			<link>http://www.harvesting-evidence.org/community/news-articles/single-news/news/new-web-site-launched.html</link>
			<description>Harvesting Evidence has been launched today.
</description>
			<content:encoded><![CDATA[<p class="bodytext">A new website, 'Harvesting Evidence' has been launched in a pilot phase today. The site is a long term project supported by The GAVI Alliance, and implemented by the Swiss Centre for International Health / Swiss Tropical Institute in collaboration with the Effective Health Care Research Intiative (Liverpool School of Tropical Medicine), Liverpool Associates in Tropical Health and the University of Cape Town.</p>]]></content:encoded>
			
			
			<pubDate>Wed, 15 Jul 2009 00:00:00 +0200</pubDate>
			
		</item>
		
	</channel>
</rss>