<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
	<channel>
		
		<title>Harvesting Evidence</title>
		<link>http://www.harvesting-evidence.org/</link>
		<description>PT: Latest news.</description>
		<language>en</language>
		<image>
			<title>Harvesting Evidence</title>
			<url>http://www.harvesting-evidence.org/EXT:tt_news/ext_icon.gif</url>
			<link>http://www.harvesting-evidence.org/</link>
			<width></width>
			<height></height>
			<description>PT: Latest news.</description>
		</image>
		<generator>TYPO3 - get.content.right</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
		
		
		
		<lastBuildDate>Wed, 15 Jul 2009 00:00:00 +0200</lastBuildDate>
		
		
	</channel>
</rss>